---
  log: "logs/main.log"
  log-level: "error"
  server:
    address: "localhost:8000"
    write-time-out: 3
    read-time-out: 3
  db:
    filename: databases/data.db
  authentication:
    config: "./authentication.yaml"
  authorization:
    cacheDuration: 5m
    cacheCleanup: 10m
  scrapers:
    match: 
      url: "http://www.sumo.or.jp/EnHonbashoMain/torikumi_ajax"
      host: "www.sumo.or.jp"